language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.8"
  
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create -f environment.yml
  - conda activate ecv2
  - python setup.py install

script:
  - pytest
